export const groupMixOptions = [
  { id: "disable", label: "OFF", weight: 0 },
  { id: "light", label: "少し", weight: 1 },
  { id: "medium", label: "中くらい", weight: 2 },
  { id: "heavy", label: "たくさん", weight: 4 },
];

export const defaultGroupMix = {
  normal: "medium",
  romance: "medium",
  spicy: "light",
  adult: "disable",
  kink: "disable",
};

export const questionGroups = [
  {
    id: "normal",
    label: "普通",
    summary: "性格、距離感、会話テンポの相性",
    questions: [
      q("normal_pace", "straight", "ノリで動きたい", "じっくり考えたい"),
      q("normal_plan", "straight", "予定を決めたい", "流れに任せたい", "遊びに行くなら？"),
      q("normal_chat", "straight", "ずっと話したい", "沈黙も平気", "一緒にいる時間は？"),
      q("normal_group", "straight", "大人数が好き", "少人数が好き"),
      q("normal_weekend", "straight", "アウトドア", "インドア", "休みの日は？"),
      q("normal_energy", "straight", "テンション高め", "落ち着き重視"),
      q("normal_decide", "reverse", "決めたい", "決めてもらいたい"),
      q("normal_listen", "reverse", "話したい", "聞きたい"),
      q("normal_lead", "reverse", "引っ張りたい", "任せたい"),
      q("normal_care", "reverse", "世話を焼きたい", "世話を焼かれたい"),
      q("normal_message", "straight", "連絡は多め", "連絡は少なめ"),
      q("normal_mood", "straight", "言葉で伝えたい", "空気で伝えたい"),
      q("normal_food", "straight", "新しい店に行きたい", "いつもの店が好き", "ごはんに行くなら？"),
      q("normal_money", "straight", "ちょっと贅沢したい", "ほどほどが落ち着く"),
      q("normal_photo", "straight", "写真を撮りたい", "目に焼き付けたい"),
      q("normal_joke", "straight", "ボケたい", "ツッコミたい"),
      q("normal_help", "reverse", "助けたい", "助けられたい"),
      q("normal_praise", "reverse", "褒めたい", "褒められたい"),
      q("normal_speed", "straight", "即レス派", "ゆっくり返信派"),
      q("normal_room", "straight", "にぎやかが好き", "静かが好き"),
      q("normal_morning", "straight", "朝型人間", "夜型人間"),
      q("normal_cook", "straight", "自炊することが多い", "外食・お弁当が多い"),
      q("normal_drink", "straight", "お酒をよく飲む", "お酒はあまり飲まない"),
      q("normal_clean", "straight", "こまめに掃除する", "まとめて一気に掃除する"),
      q("normal_shop", "straight", "計画的に買い物する", "直感で買っちゃう"),
      q("normal_call", "straight", "電話でのやりとりが好き", "テキストでのやりとりが好き"),
      q("normal_time", "straight", "集合時間はきっちり守る", "少しルーズになりがち"),
      q("normal_anger", "straight", "怒るとすぐ顔に出る", "怒っても一旦我慢する"),
      q("normal_apology", "straight", "喧嘩したらすぐ謝れる", "納得するまで話し合いたい"),
      q("normal_hobby", "straight", "趣味は浅く広く", "趣味は狭く深く"),
      q("normal_trip", "straight", "旅行は観光地を巡りたい", "旅行はホテルでゆっくりしたい"),
      q("normal_pay", "straight", "お金はきっちり割り勘したい", "お金はざっくりでいい"),
      q("normal_stress", "straight", "ストレスは人に話して発散", "ストレスは一人で発散"),
      q("normal_novelty", "straight", "新しいもの・流行りが好き", "昔からの定番が好き"),
      q("normal_sns", "straight", "SNSはよく見る・投稿する", "SNSはあまり見ない"),
      q("normal_season", "straight", "夏の方が好き", "冬の方が好き"),
      q("normal_movie", "straight", "映画は映画館で観たい", "家でゆっくり観たい", "映画を観るなら？"),
      q("normal_pet", "straight", "どちらかというと犬派", "どちらかというと猫派"),
      q("normal_memory", "straight", "写真や思い出はとっておく", "過去のものは割と捨てる"),
      q("normal_rule", "straight", "ルールやマナーは絶対守る", "状況に合わせて柔軟でいい"),
    ],
  },
  {
    id: "romance",
    label: "恋愛",
    summary: "甘え方、恋愛テンポ、距離感",
    questions: [
      q("romance_spoil", "reverse", "甘やかしたい", "甘やかされたい"),
      q("romance_praise", "reverse", "好きと言いたい", "好きと言われたい"),
      q("romance_contact", "straight", "毎日連絡したい", "たまにでいい"),
      q("romance_date", "straight", "予定を詰めたい", "余白を楽しみたい", "デートの予定は？"),
      q("romance_public", "straight", "外でも距離近め", "外では控えめ"),
      q("romance_private", "straight", "二人きりが好き", "みんなでいるのが好き", "好きな距離感は？"),
      q("romance_jealous", "straight", "少し嫉妬する", "あまり嫉妬しない"),
      q("romance_age", "reverse", "年上が好き", "年下が好き"),
      q("romance_depend", "reverse", "頼られたい", "頼りたい"),
      q("romance_invite", "reverse", "誘いたい", "誘われたい"),
      q("romance_confess", "reverse", "気持ちを伝えたい", "気持ちを引き出したい"),
      q("romance_tease", "reverse", "からかいたい", "からかわれたい"),
      q("romance_gift", "reverse", "プレゼントしたい", "プレゼントされたい"),
      q("romance_walk", "straight", "手をつなぎたい", "隣を歩くだけでいい"),
      q("romance_drink", "straight", "酔うと甘える", "酔うと冷静になる"),
      q("romance_secret", "straight", "秘密っぽい恋が好き", "堂々としたい"),
      q("romance_words", "straight", "言葉がほしい", "行動でわかる"),
      q("romance_mood", "straight", "ロマンチック重視", "自然体重視"),
      q("romance_distance", "straight", "距離は近いほどいい", "少し余白がほしい"),
      q("romance_after", "straight", "余韻を話したい", "余韻は静かに味わいたい"),
    ],
  },
  {
    id: "spicy",
    label: "ちょい攻め",
    summary: "少し照れる、少し踏み込む質問",
    questions: [
      q("spicy_praise", "reverse", "褒め倒したい", "褒め倒されたい"),
      q("spicy_tease", "reverse", "いじりたい", "いじられたい"),
      q("spicy_lead", "reverse", "リードしたい", "リードされたい"),
      q("spicy_stare", "reverse", "見つめたい", "見つめられたい"),
      q("spicy_whisper", "reverse", "耳元で言いたい", "耳元で言われたい"),
      q("spicy_request", "reverse", "お願いしたい", "お願いされたい"),
      q("spicy_attention", "straight", "注目されると燃える", "二人だけがいい"),
      q("spicy_secret", "straight", "秘密感が好き", "オープンな方が好き"),
      q("spicy_shy", "straight", "照れ顔に弱い", "余裕のある顔に弱い"),
      q("spicy_push", "straight", "少し押されたい", "自分のペースがいい"),
      q("spicy_word", "straight", "言葉でドキッとしたい", "雰囲気でドキッとしたい"),
      q("spicy_distance", "straight", "近距離が好き", "少し離れていたい", "ドキッとする距離は？"),
      q("spicy_game", "straight", "勝負で熱くなる", "負けても楽しむ"),
      q("spicy_dare", "reverse", "言わせたい", "言わされたい"),
      q("spicy_choice", "reverse", "選ばせたい", "選ばれたい"),
      q("spicy_guard", "reverse", "守りたい", "守られたい"),
      q("spicy_drink", "straight", "酔うと大胆", "酔うと甘い"),
      q("spicy_signal", "straight", "わかりやすい合図が好き", "さりげない合図が好き"),
      q("spicy_tension", "straight", "じわじわが好き", "一気に盛り上がりたい"),
      q("spicy_aftercare", "reverse", "フォローしたい", "フォローされたい"),
    ],
  },
  {
    id: "adult",
    label: "アダルト",
    summary: "夜の雰囲気と主導権の好み",
    questions: [
      q("adult_mood", "straight", "暗めの雰囲気が好き", "明るい雰囲気が好き", "夜の雰囲気は？"),
      q("adult_control", "reverse", "主導したい", "主導されたい"),
      q("adult_slow", "straight", "ゆっくり進めたい", "テンポよく進めたい"),
      q("adult_whisper", "reverse", "耳元で囁きたい", "耳元で囁かれたい"),
      q("adult_silence", "straight", "静かな空気が好き", "声がある方が好き"),
      q("adult_eye", "straight", "ずっと見つめ合いたい", "恥ずかしいから目を閉じたい"),
      q("adult_safe", "straight", "安心感・包容力が大事", "少しの緊張感がスパイス"),
      q("adult_command", "reverse", "お願いを聞かせたい", "お願いを聞きたい"),
      q("adult_pace", "reverse", "ペースを作りたい", "ペースを作られたい"),
      q("adult_active", "reverse", "自分から求めたい", "相手から求められたい"),
      q("adult_react", "reverse", "反応を見たい", "反応を見られたい"),
      q("adult_gentle", "straight", "優しさ重視", "激しさ重視"),
      q("adult_location", "straight", "ベッドでじっくりしたい", "ベッド以外でもしたい"),
      q("adult_switch", "straight", "立場は固定したい", "たまに入れ替えたい"),
      q("adult_touch", "reverse", "たくさん触れたい", "たくさん触れられたい"),
      q("adult_foreplay", "straight", "前戯は長めがいい", "前戯は短めでいい"),
      q("adult_reassure", "reverse", "安心させたい", "安心させられたい"),
      q("adult_after", "straight", "終わった後もくっつきたい", "終わったら少し離れたい"),
      q("adult_limit", "straight", "NGなことは先に話したい", "流れや雰囲気で判断したい"),
      q("adult_frequency", "straight", "頻度は多めがいい", "頻度は少なめでいい"),
    ],
  },
  {
    id: "kink",
    label: "性癖",
    summary: "かなり個性が出る、攻めた好み",
    questions: [
      q("kink_bondage", "reverse", "縛りたい・動けなくしたい", "縛られたい・動けなくされたい"),
      q("kink_pain", "reverse", "痛みを与えたい", "痛みを感じたい"),
      q("kink_mark", "reverse", "キスマークや跡を残したい", "キスマークや跡を残されたい"),
      q("kink_degrade", "reverse", "言葉で責めたい・辱めたい", "言葉で責められたい・辱められたい"),
      q("kink_blindfold", "reverse", "目隠し等で感覚を奪いたい", "目隠し等で感覚を奪われたい"),
      q("kink_master", "reverse", "完全に支配したい", "完全に服従したい"),
      q("kink_pet", "reverse", "飼い主になりたい", "ペットになりたい"),
      q("kink_edge", "reverse", "限界までおあずけしたい", "限界まで焦らされたい"),
      q("kink_force", "reverse", "抵抗をねじ伏せたい", "強引に奪われたい"),
      q("kink_toy", "reverse", "道具を使って責めたい", "道具で責められたい"),
      q("kink_public", "straight", "誰かに見られるスリルが欲しい", "絶対に密室がいい", "プレイ環境は？"),
      q("kink_record", "reverse", "行為を撮影・記録したい", "行為を撮影・記録されたい"),
      q("kink_neglect", "reverse", "放置して見下したい", "放置されて見下されたい"),
      q("kink_serve", "reverse", "徹底的に奉仕させたい", "徹底的に奉仕したい"),
      q("kink_expose", "reverse", "恥ずかしい格好をさせたい", "恥ずかしい格好をさせられたい"),
      q("kink_breath", "reverse", "首を絞めるなど息を奪いたい", "首を絞められるなど息を奪われたい"),
      q("kink_sleep", "reverse", "相手が寝ている間に好きにしたい", "自分が寝ている間に好きにされたい"),
      q("kink_messy", "reverse", "ぐちゃぐちゃに汚したい", "ぐちゃぐちゃに汚されたい"),
      q("kink_punish", "reverse", "お仕置き・罰を与えたい", "お仕置き・罰を与えられたい"),
      q("kink_share", "straight", "他の人を交えるのも興味がある", "絶対に2人だけがいい", "プレイの範囲は？"),
    ],
  },
];

function q(id, type, left, right, prompt = "どっち寄り？") {
  return { id, type, prompt, left, right };
}
