export const groupMixOptions = [
  { id: "disable", label: "OFF", weight: 0 },
  { id: "light", label: "少し", weight: 1 },
  { id: "medium", label: "中くらい", weight: 2 },
  { id: "heavy", label: "たくさん", weight: 4 },
];

export const defaultGroupMix = {
  normal: "medium",
  romance: "medium",
  spicy: "light",
  adult: "disable",
  kink: "disable",
};

export const questionGroups = [
  {
    id: "normal",
    label: "普通",
    summary: "性格、距離感、会話テンポの相性",
    questions: [
      q("normal_pace", "straight", "ノリで動きたい", "じっくり考えたい"),
      q("normal_plan", "straight", "予定を決めたい", "流れに任せたい", "遊びに行くなら？"),
      q("normal_chat", "straight", "ずっと話したい", "沈黙も平気", "一緒にいる時間は？"),
      q("normal_group", "straight", "大人数が好き", "少人数が好き"),
      q("normal_weekend", "straight", "アウトドア", "インドア", "休みの日は？"),
      q("normal_energy", "straight", "テンション高め", "落ち着き重視"),
      q("normal_decide", "reverse", "決めたい", "決めてもらいたい"),
      q("normal_listen", "reverse", "話したい", "聞きたい"),
      q("normal_lead", "reverse", "引っ張りたい", "任せたい"),
      q("normal_care", "reverse", "世話を焼きたい", "世話を焼かれたい"),
      q("normal_message", "straight", "連絡は多め", "連絡は少なめ"),
      q("normal_mood", "straight", "言葉で伝えたい", "空気で伝えたい"),
      q("normal_food", "straight", "新しい店に行きたい", "いつもの店が好き", "ごはんに行くなら？"),
      q("normal_money", "straight", "ちょっと贅沢したい", "ほどほどが落ち着く"),
      q("normal_photo", "straight", "写真を撮りたい", "目に焼き付けたい"),
      q("normal_joke", "straight", "ボケたい", "ツッコミたい"),
      q("normal_help", "reverse", "助けたい", "助けられたい"),
      q("normal_praise", "reverse", "褒めたい", "褒められたい"),
      q("normal_speed", "straight", "即レス派", "ゆっくり返信派"),
      q("normal_room", "straight", "にぎやかが好き", "静かが好き"),
    ],
  },
  {
    id: "romance",
    label: "恋愛",
    summary: "甘え方、恋愛テンポ、距離感",
    questions: [
      q("romance_spoil", "reverse", "甘やかしたい", "甘やかされたい"),
      q("romance_praise", "reverse", "好きと言いたい", "好きと言われたい"),
      q("romance_contact", "straight", "毎日連絡したい", "たまにでいい"),
      q("romance_date", "straight", "予定を詰めたい", "余白を楽しみたい", "デートの予定は？"),
      q("romance_public", "straight", "外でも距離近め", "外では控えめ"),
      q("romance_private", "straight", "二人きりが好き", "みんなでいるのが好き", "好きな距離感は？"),
      q("romance_jealous", "straight", "少し嫉妬する", "あまり嫉妬しない"),
      q("romance_age", "reverse", "年上が好き", "年下が好き"),
      q("romance_depend", "reverse", "頼られたい", "頼りたい"),
      q("romance_invite", "reverse", "誘いたい", "誘われたい"),
      q("romance_confess", "reverse", "気持ちを伝えたい", "気持ちを引き出したい"),
      q("romance_tease", "reverse", "からかいたい", "からかわれたい"),
      q("romance_gift", "reverse", "プレゼントしたい", "プレゼントされたい"),
      q("romance_walk", "straight", "手をつなぎたい", "隣を歩くだけでいい"),
      q("romance_drink", "straight", "酔うと甘える", "酔うと冷静になる"),
      q("romance_secret", "straight", "秘密っぽい恋が好き", "堂々としたい"),
      q("romance_words", "straight", "言葉がほしい", "行動でわかる"),
      q("romance_mood", "straight", "ロマンチック重視", "自然体重視"),
      q("romance_distance", "straight", "距離は近いほどいい", "少し余白がほしい"),
      q("romance_after", "straight", "余韻を話したい", "余韻は静かに味わいたい"),
    ],
  },
  {
    id: "spicy",
    label: "ちょい攻め",
    summary: "少し照れる、少し踏み込む質問",
    questions: [
      q("spicy_praise", "reverse", "褒め倒したい", "褒め倒されたい"),
      q("spicy_tease", "reverse", "いじりたい", "いじられたい"),
      q("spicy_lead", "reverse", "リードしたい", "リードされたい"),
      q("spicy_stare", "reverse", "見つめたい", "見つめられたい"),
      q("spicy_whisper", "reverse", "耳元で言いたい", "耳元で言われたい"),
      q("spicy_request", "reverse", "お願いしたい", "お願いされたい"),
      q("spicy_attention", "straight", "注目されると燃える", "二人だけがいい"),
      q("spicy_secret", "straight", "秘密感が好き", "オープンな方が好き"),
      q("spicy_shy", "straight", "照れ顔に弱い", "余裕のある顔に弱い"),
      q("spicy_push", "straight", "少し押されたい", "自分のペースがいい"),
      q("spicy_word", "straight", "言葉でドキッとしたい", "雰囲気でドキッとしたい"),
      q("spicy_distance", "straight", "近距離が好き", "少し離れていたい", "ドキッとする距離は？"),
      q("spicy_game", "straight", "勝負で熱くなる", "負けても楽しむ"),
      q("spicy_dare", "reverse", "言わせたい", "言わされたい"),
      q("spicy_choice", "reverse", "選ばせたい", "選ばれたい"),
      q("spicy_guard", "reverse", "守りたい", "守られたい"),
      q("spicy_drink", "straight", "酔うと大胆", "酔うと甘い"),
      q("spicy_signal", "straight", "わかりやすい合図が好き", "さりげない合図が好き"),
      q("spicy_tension", "straight", "じわじわが好き", "一気に盛り上がりたい"),
      q("spicy_aftercare", "reverse", "フォローしたい", "フォローされたい"),
    ],
  },
  {
    id: "adult",
    label: "アダルト",
    summary: "夜の雰囲気と主導権の好み",
    questions: [
      q("adult_mood", "straight", "暗めの雰囲気が好き", "明るい雰囲気が好き", "夜の雰囲気は？"),
      q("adult_control", "reverse", "主導したい", "主導されたい"),
      q("adult_slow", "straight", "ゆっくり進めたい", "テンポよく進めたい"),
      q("adult_words", "reverse", "言葉で攻めたい", "言葉で攻められたい"),
      q("adult_silence", "straight", "静かな空気が好き", "声がある方が好き"),
      q("adult_eye", "reverse", "目を逸らさせたい", "見つめられたい"),
      q("adult_secret", "straight", "秘密っぽい方が燃える", "安心感が大事"),
      q("adult_command", "reverse", "お願いを聞かせたい", "お願いを聞きたい"),
      q("adult_pace", "reverse", "ペースを作りたい", "ペースを作られたい"),
      q("adult_distance", "straight", "距離感は近め", "余白がある方がいい"),
      q("adult_confess", "reverse", "言わせたい", "言いたい"),
      q("adult_react", "reverse", "反応を見たい", "反応を見られたい"),
      q("adult_gentle", "straight", "優しさ重視", "刺激重視"),
      q("adult_private", "straight", "完全に二人きりがいい", "少しスリルがほしい"),
      q("adult_switch", "straight", "立場は固定したい", "たまに入れ替えたい"),
      q("adult_touch", "reverse", "触れたい", "触れられたい"),
      q("adult_wait", "reverse", "待たせたい", "待たされたい"),
      q("adult_reassure", "reverse", "安心させたい", "安心させられたい"),
      q("adult_after", "straight", "終わった後も甘い方がいい", "切り替え早めがいい"),
      q("adult_limit", "straight", "境界線は先に決めたい", "流れで決めたい"),
    ],
  },
  {
    id: "kink",
    label: "性癖",
    summary: "かなり個性が出る、攻めた好み",
    questions: [
      q("kink_order", "reverse", "従わせたい", "従いたい"),
      q("kink_rule", "straight", "ルールがあると燃える", "自由な方が燃える"),
      q("kink_watch", "reverse", "観察したい", "観察されたい"),
      q("kink_blush", "reverse", "照れさせたい", "照れさせられたい"),
      q("kink_power", "straight", "強めが好き", "やわらかめが好き", "攻め方の温度は？"),
      q("kink_name", "straight", "呼び方にこだわる", "呼び方は自然でいい"),
      q("kink_secret", "straight", "秘密の合図が好き", "はっきり言う方が好き"),
      q("kink_forbid", "reverse", "焦らしたい", "焦らされたい"),
      q("kink_choice", "reverse", "選択肢を渡したい", "選択肢を渡されたい"),
      q("kink_mock", "reverse", "少し意地悪したい", "少し意地悪されたい"),
      q("kink_devote", "reverse", "尽くしたい", "尽くされたい"),
      q("kink_check", "reverse", "確認したい", "確認されたい"),
      q("kink_tension", "straight", "緊張感が好き", "安心感が好き"),
      q("kink_role", "straight", "役割があると楽しい", "自然体が楽しい"),
      q("kink_voice", "straight", "声に弱い", "表情に弱い"),
      q("kink_distance", "straight", "近すぎるくらいが好き", "少し遠い方が好き"),
      q("kink_public", "straight", "ギリギリ感が好き", "安全圏が好き"),
      q("kink_after", "reverse", "甘やかして戻したい", "甘やかされて戻りたい"),
      q("kink_switch", "straight", "攻守を決めたい", "攻守を揺らしたい"),
      q("kink_trust", "straight", "信頼があれば攻めたい", "信頼があるほど甘えたい"),
    ],
  },
];

function q(id, type, left, right, prompt = "どっち寄り？") {
  return { id, type, prompt, left, right };
}
